version: "3.8"

services:
  prop-cloud-backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    command: uvicorn app/main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://prop-cloud-db:27017/${MONGO_INITDB_DATABASE}

  prop-cloud-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db